name: pecon_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.3
  flutter_screenutil: ^5.9.3
  intl: ^0.17.0
  carousel_slider: ^5.1.1
  image_picker: ^1.2.1
  image_cropper: ^11.0.0
  dio: ^5.9.0
  get_storage: ^2.1.1
  url_launcher: ^6.3.2
  flutter_markdown: ^0.7.7+1
  html2md: ^1.3.2
  confetti: ^0.8.0
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  cached_network_image: ^3.4.1
  flutter_inappwebview: ^6.1.5

  # Firebase
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0

  # Notifications
  flutter_local_notifications: ^19.5.0

  faded: ^1.1.1
  connectivity_plus: ^7.0.0
  new_version_plus: ^0.1.0
  version: ^3.0.2
  open_store: ^0.5.0
  video_player: ^2.10.1
  dropdown_button2: ^2.3.9

  # Scanner (updated for Flutter 3+)
  qr_code_scanner_plus: ^2.0.14   # Keep if you need it
  qr_code_tools: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
